#!/bin/bash
# generate-project-claude.sh <project-name>
# Generate a CLAUDE.md for a project repo by injecting domain-specific L3 rules,
# L4 policies, and L5/L6 traits/values.
#
# Project type is read from projects/<name>/wiki/INDEX.md frontmatter field: project_type
# Types: code | paper | research | mixed
#
# Rule injection logic:
#   code    → engineering/ rules
#   paper   → paper-writing/ + research/ rules
#   research/mixed → engineering/ + research/ rules
#   ALL types also get paper-reading/ rules (reading is universal)
#   ALL types get L4 policies, L5 traits, L6 values

set -euo pipefail

PROJECT="${1:-}"
if [ -z "$PROJECT" ]; then
  echo "Usage: tools/generate-project-claude.sh <project-name>" >&2
  exit 1
fi

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$ROOT"

INDEX="projects/$PROJECT/wiki/INDEX.md"
if [ ! -f "$INDEX" ]; then
  echo "Error: $INDEX not found" >&2
  exit 1
fi

# Detect project type from frontmatter (default: mixed)
PROJECT_TYPE=$(sed -n '/^---$/,/^---$/{/^project_type:/s/.*: *//p}' "$INDEX" | head -1)
PROJECT_TYPE="${PROJECT_TYPE:-mixed}"

echo "Project: $PROJECT (type: $PROJECT_TYPE)"

# Determine which L3 domain directories to include
DOMAINS="paper-reading"  # always included
case "$PROJECT_TYPE" in
  code)      DOMAINS="$DOMAINS engineering" ;;
  paper)     DOMAINS="$DOMAINS paper-writing research" ;;
  research)  DOMAINS="$DOMAINS engineering research" ;;
  mixed)     DOMAINS="$DOMAINS engineering research" ;;
esac

# Read project repo path
SOURCE_PATH=$(head -1 "projects/$PROJECT/source_path.txt" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
SOURCE_PATH="${SOURCE_PATH/#\~/$HOME}"

OUTPUT="$SOURCE_PATH/CLAUDE.md"

echo "Domains: $DOMAINS"
echo "Output: $OUTPUT"

# Build CLAUDE.md content
{
  echo "# $PROJECT — Agent-Injected Rules"
  echo ""
  echo "> Auto-generated by MyJarvis. Do not edit manually."
  echo "> Last generated: $(date +%Y-%m-%d)"
  echo "> Project type: $PROJECT_TYPE"
  echo ""

  # L3 Domain rules
  echo "## L3 Domain Rules"
  echo ""
  for domain in $DOMAINS; do
    dir="wiki/rules/$domain"
    [ -d "$dir" ] || continue
    rules=$(find "$dir" -name "*.md" -not -name ".gitkeep" 2>/dev/null)
    [ -z "$rules" ] && continue
    echo "### Domain: $domain"
    echo ""
    for rule_file in $rules; do
      rule_name=$(sed -n '/^# /{s/^# //;p;q}' "$rule_file")
      statement=$(sed -n '/^## Statement/{n;p}' "$rule_file")
      if [ -z "$statement" ]; then
        # Try alternative format (numbered list after ## 规则 or ## Statement)
        statement=$(sed -n '/^## /{/Statement\|规则/!d;n;p}' "$rule_file" | head -1)
      fi
      echo "- **$rule_name**: $statement"
    done
    echo ""
  done

  # L4 Policies
  echo "## L4 Policies (cross-domain)"
  echo ""
  for policy_file in wiki/policies/*.md; do
    [ -f "$policy_file" ] || continue
    policy_name=$(sed -n '/^# /{s/^# //;p;q}' "$policy_file")
    statement=$(sed -n '/^## Statement/{n;p}' "$policy_file")
    applies=$(sed -n '/^---$/,/^---$/{/^applies_to:/s/.*: *//p}' "$policy_file" | head -1)
    echo "- **$policy_name** (applies to: $applies): $statement"
  done
  echo ""

  # L5 Traits
  echo "## L5 Traits"
  echo ""
  for trait_file in wiki/traits/*.md; do
    [ -f "$trait_file" ] || continue
    trait_name=$(sed -n '/^# /{s/^# //;p;q}' "$trait_file")
    statement=$(sed -n '/^## Statement/{n;p}' "$trait_file")
    echo "- **$trait_name**: $statement"
  done
  echo ""

  # L6 Values
  echo "## L6 Values"
  echo ""
  for value_file in wiki/values/*.md; do
    [ -f "$value_file" ] || continue
    value_name=$(sed -n '/^# /{s/^# //;p;q}' "$value_file")
    statement=$(sed -n '/^## Statement/{n;p}' "$value_file")
    echo "- **$value_name**: $statement"
  done

  # Current project state (assembled from wiki)
  AGENT_HOME=$(pwd)
  PROJ_WIKI="projects/$PROJECT/wiki"

  echo "## Current project state"
  echo ""
  echo "> Auto-assembled from project wiki. Regenerated on $(date +%Y-%m-%d)."
  echo ""

  # Recent progress (last ~20 lines of progress.md)
  if [ -f "$PROJ_WIKI/progress.md" ]; then
    echo "### Recent progress"
    echo ""
    # Get the last ## section (most recent)
    tail -30 "$PROJ_WIKI/progress.md" | head -25
    echo ""
  fi

  # Active backlog
  if [ -f "$PROJ_WIKI/backlog.md" ]; then
    echo "### Active tasks"
    echo ""
    sed -n '/^## Active/,/^## /{/^## Active/d;/^## /d;p}' "$PROJ_WIKI/backlog.md" | head -15
    echo ""
  fi

  # Open constraints
  if [ -f "$PROJ_WIKI/constraints.md" ]; then
    open_count=$(grep -c "| open |" "$PROJ_WIKI/constraints.md" 2>/dev/null || echo "0")
    if [ "$open_count" -gt 0 ]; then
      echo "### Open constraints ($open_count)"
      echo ""
      head -1 "$PROJ_WIKI/constraints.md" | grep -q "^|" && grep "^|" "$PROJ_WIKI/constraints.md" | head -1  # header
      grep "^|" "$PROJ_WIKI/constraints.md" | head -2 | tail -1  # separator
      grep "| open |" "$PROJ_WIKI/constraints.md"
      echo ""
    fi
  fi
  cat << KPROTO

---

## Knowledge access protocol

> AUTO-GENERATED — tells this project's Claude Code where to find agent-system knowledge.
> Follow links in wiki pages first (deterministic). Only grep/search when links are insufficient.

When you need information beyond this CLAUDE.md, use these paths:

| # | Need | Where to look | When to use |
|---|------|---------------|-------------|
| 1 | **历史决策** | \`${AGENT_HOME}/projects/${PROJECT}/wiki/decisions.md\` | 做技术选型前，先查之前类似的决策和被否决的方案 |
| 2 | **相关论文** | \`${AGENT_HOME}/projects/${PROJECT}/wiki/INDEX.md\` → \`## Related literature\` → follow links to \`wiki/knowledge/papers-<topic>.md\` | 需要文献支撑、方法论参考、或检查是否有人做过类似工作 |
| 3 | **跨项目知识** | \`grep -r <keyword> ${AGENT_HOME}/projects/*/wiki/\` | 怀疑其他项目有可复用的方案或经验 |
| 4 | **历史解法** | \`grep -r <keyword> ${AGENT_HOME}/raw/claude-sessions/\` | 遇到之前 session 可能解决过的问题 |
| 5 | **用户论文评价** | \`${AGENT_HOME}/wiki/knowledge/papers-<topic>.md\` per-paper notes | 需要用户对某篇论文的个人观点（非 abstract） |
| 6 | **用户偏好/traits** | \`${AGENT_HOME}/wiki/traits/\` and \`${AGENT_HOME}/wiki/policies/\` | 需要理解用户的工作风格（已摘要在本文件 L5/L6 sections，读原文件获取完整 rationale） |

**Retrieval priority**: wiki page links (deterministic, fast) > grep (broad) > ollama semantic search (last resort).
KPROTO

  # Experiment review protocol (for research/paper/mixed projects)
  case "$PROJECT_TYPE" in
    code) ;; # skip for pure code projects
    *)
      cat << REVIEW

---

## Experiment design review protocol

> AUTO-GENERATED — triggers Codex review after research design decisions.
> Full protocol: \`${AGENT_HOME}/docs/codex-audit.md\` §4

After making any of these design decisions, **automatically** trigger Codex review:
1. Metric definition or redesign
2. Experiment parameter/configuration choices
3. Evaluation methodology design
4. Data processing pipeline design
5. Statistical analysis method selection
6. Claim formulation

**Flow**:
1. Package: decision + rationale + implementation + alternatives considered + project context
2. Send to Codex via MCP for adversarial review
3. Present Codex concerns to user (each tagged [high/medium/low])
4. User acc/rej/edit each concern
5. Adjust design based on accepted concerns, log all decisions to \`decisions.md\`

**Do NOT trigger for**: pure implementation (making code work), formatting, docs updates.
**Degradation**: Codex unavailable → skip review, note "Codex design review 未完成" and proceed.
REVIEW
      ;;
  esac

  # Session-end protocol (always appended)
  cat << PROTO

---

## Session-end protocol

> AUTO-GENERATED — ensures project sessions feed back to agent-system.
> Do not edit. Regenerate with: tools/generate-project-claude.sh $PROJECT

Every session ending, execute these steps:

### Step 1: Session summary → agent-system
Write to \`${AGENT_HOME}/raw/claude-sessions/\$(date +%Y-%m-%d-%H%M)-${PROJECT}.md\`:
\`\`\`yaml
---
source: project-session
project: ${PROJECT}
session_date: \$(date +%Y-%m-%d)
duration_estimate: ~Xh
---
\`\`\`
Content:
- **Factual**: what was done, what was tried, results, edge cases, key numbers
- **Rule signals**: user preferences, methodology decisions, rejected approaches

### Step 2: Update project wiki
Update \`${AGENT_HOME}/projects/${PROJECT}/wiki/\`:
- \`progress.md\`: append today's progress
- \`decisions.md\`: append new decisions (if any)
- \`architecture.md\`: update if structural changes
- \`backlog.md\`: completed tasks → Done (with date), new tasks → Active/Queued/Ideas
- \`constraints.md\`: append newly discovered edge cases or constraints

### Step 3: Append to daily log
Append to \`${AGENT_HOME}/raw/daily/\$(date +%Y-%m-%d).md\`:
\`\`\`markdown
## HH:MM - ${PROJECT} session
- **Project**: ${PROJECT}
- **Type**: coding | writing | debugging | design | review
- **Status**: done | partial
- **Duration**: ~Xh
- **Summary**: one-line summary
\`\`\`

### Step 4: Immediate CLAUDE.md regeneration
Run: \`bash ${AGENT_HOME}/tools/generate-project-claude.sh ${PROJECT}\`
Ensures the next session reads the latest project state. Do not wait for wrap-up or compile.
PROTO

} > "$OUTPUT"

echo "Generated: $OUTPUT ($(wc -l < "$OUTPUT") lines)"
